In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from ISLP.models import (ModelSpec as MS, summarize,poly)
from matplotlib.pyplot import subplots
from statsmodels.stats.anova import anova_lm
import math

In [2]:
rng = np.random.default_rng(1)
x = rng.normal(size=100)
y = 2 * x + rng.normal(size=100)
y

array([ 0.03988737,  2.50568108,  0.53528207, -1.93716122,  3.02955534,
        1.27567873, -1.94962761, -0.35208242,  2.48252891,  0.4769728 ,
       -0.63172047,  1.23768306, -1.6643195 ,  0.52632237, -0.93031044,
        1.21144201, -0.63513551, -0.1153454 , -2.59768365,  0.15150496,
        1.54022187, -2.07589185,  0.1218984 ,  2.63032739, -2.87442714,
       -4.77895134, -1.60023994, -0.25541189, -0.4134356 , -0.07138162,
        3.88756004, -1.69203944, -1.16051238,  4.36342606,  1.11687273,
        0.48145564, -1.347839  , -4.24655001,  0.34144447, -0.90583805,
       -3.54759848,  0.09050849, -0.19727158, -1.94340527,  0.31499648,
       -0.22989095, -0.15736289, -0.58743458,  1.46991199,  0.62303718,
        1.47503921, -2.2268954 ,  0.40722562, -1.90335511,  1.36777589,
       -0.51627458,  0.6533985 ,  0.11994898, -4.63532214, -0.62936588,
        1.00777098,  0.30891936, -2.59373117, -1.98323503,  1.09932082,
       -0.26984166,  2.44348508,  1.72820652, -3.88998483,  0.38279704,
        2.37679539, -0.48631631, -1.65165698,  1.67845359, -1.16395703,
        2.6213951 , -1.26517069, -4.13679524,  0.41772963,  0.4256697 ,
        2.04367579,  0.54842501, -4.19391877,  0.48124118,  2.64783669,
        0.22023536, -2.06012465,  0.08488166, -0.66358402,  1.10543908,
        1.29341284,  1.73924185,  0.77249799, -3.22898157,  2.15318819,
       -6.11917605,  0.83232735,  0.23410608, -2.30229247, -0.3994975 ])

In [3]:
x

array([ 3.45584192e-01,  8.21618144e-01,  3.30437076e-01, -1.30315723e+00,
        9.05355867e-01,  4.46374572e-01, -5.36953235e-01,  5.81118104e-01,
        3.64572396e-01,  2.94132497e-01,  2.84222413e-02,  5.46712987e-01,
       -7.36454087e-01, -1.62909948e-01, -4.82119313e-01,  5.98846213e-01,
        3.97221075e-02, -2.92456751e-01, -7.81908462e-01, -2.57192241e-01,
        8.14218052e-03, -2.75602905e-01,  1.29406381e+00,  1.00672432e+00,
       -2.71116248e+00, -1.88901325e+00, -1.74772092e-01, -4.22190412e-01,
        2.13642997e-01,  2.17321931e-01,  2.11783876e+00, -1.11202076e+00,
       -3.77605007e-01,  2.04277161e+00,  6.46702996e-01,  6.63063372e-01,
       -5.14006372e-01, -1.64807517e+00,  1.67464744e-01,  1.09014088e-01,
       -1.22735205e+00, -6.83226662e-01, -7.20436797e-02, -9.44751623e-01,
       -9.82699679e-02,  9.54830275e-02,  3.55862371e-02, -5.06291658e-01,
        5.93748072e-01,  8.91166954e-01,  3.20848305e-01, -8.18230227e-01,
        7.31652284e-01, -5.01440018e-01,  8.79160618e-01, -1.07178742e+00,
        9.14467203e-01, -2.00634546e-02, -1.24874889e+00, -3.13899472e-01,
        5.41022788e-02,  2.72791339e-01, -9.82188125e-01, -1.10737305e+00,
        1.99584533e-01, -4.66749617e-01,  2.35505612e-01,  7.59519522e-01,
       -1.64878737e+00,  2.54388117e-01,  1.22464697e+00, -2.97526844e-01,
       -8.10814583e-01,  7.52243827e-01,  2.53446516e-01,  8.95883071e-01,
       -3.45215710e-01, -1.48181827e+00, -1.10010765e-01, -4.45828153e-01,
        7.75323822e-01,  1.93632848e-01, -1.63084923e+00, -1.19516308e+00,
        8.83789037e-01,  6.79765017e-01, -6.40243366e-01, -1.04879657e-03,
        4.45573554e-01,  4.68404336e-01,  8.76242196e-01,  2.56485627e-01,
       -9.48283390e-02, -2.58848065e-01,  1.05574280e+00, -2.25085428e+00,
       -1.38655325e-01,  3.30001040e-02, -1.42534896e+00,  3.32813613e-01])

In [4]:
results = sm.OLS(y,x).fit()
summarize(results)

      coef  std err       t  P>|t|
x1  1.9762    0.117  16.898    0.0

Как мы видим и результаток коэффициент В1 для х1 в целом определен достаточно близко к оптимальному углу наклона.

In [5]:
results1 = sm.OLS(x,y).fit()
summarize(results1)

      coef  std err       t  P>|t|
x1  0.3757    0.022  16.898    0.0

Визуально Коээфициенты сильно отличаются, но можно заметить, что Т-значение одинаково

In [11]:
x1 = pd.DataFrame(x)
x1['intercept'] = 1;
results2 = sm.OLS(y,x1).fit()
summarize(results2)

             coef  std err       t  P>|t|
0          1.9686    0.118  16.734  0.000
intercept -0.0760    0.101  -0.756  0.451

In [12]:
y1 = pd.DataFrame(y)
y1['intercept'] = 1;
results3 = sm.OLS(x,y1).fit()
summarize(results3)

             coef  std err       t  P>|t|
0          0.3763    0.022  16.734  0.000
intercept  0.0095    0.044   0.216  0.829